---
- name: Add ipv6 cidr to kube-proxy
  ansible.builtin.lineinfile:
    path: /var/snap/microk8s/current/args/kube-proxy
    regexp: "^--cluster-cidr.*$"
    line: "--cluster-cidr=fd01::/64,10.1.0.0/16"
  notify: Restart Microk8s

- name: Enable dualstack in kube-proxy
  ansible.builtin.lineinfile:
    path: /var/snap/microk8s/current/args/kube-proxy
    line: '--feature-gates="IPv6DualStack=true"'
  notify: Restart Microk8s

- name: Adjust service cluster ip range in kube-apiserver
  ansible.builtin.lineinfile:
    path: /var/snap/microk8s/current/args/kube-apiserver
    regexp: "^--service-cluster-ip-range.*$"
    line: "--service-cluster-ip-range=fd98::/108,10.152.183.0/24"
  notify: Restart Microk8s

- name: Enable dualstack in kube-apiserver
  ansible.builtin.lineinfile:
    path: /var/snap/microk8s/current/args/kube-apiserver
    regexp: "^--feature-gates.*$"
    line: '--feature-gates="IPv6DualStack=true"'
  notify: Restart Microk8s

- name: Enable dualstack in kube-controller-manager
  ansible.builtin.lineinfile:
    path: /var/snap/microk8s/current/args/kube-controller-manager
    line: "{{ item }}"
  with_items:
    - '--feature-gates="IPv6DualStack=true"'
    - "--service-cluster-ip-range=fd98::/108,10.152.183.0/24"
    - "--cluster-cidr=fd01::/64,10.1.0.0/16"
  notify: Restart Microk8s

- name: Enable dualstack in kubelet
  ansible.builtin.lineinfile:
    path: /var/snap/microk8s/current/args/kubelet
    line: '--feature-gates="IPv6DualStack=true"'
  notify: Restart Microk8s

- name: Set node-ip in kubelet
  ansible.builtin.lineinfile:
    path: /var/snap/microk8s/current/args/kubelet
    regexp: "^--node-ip.*$"
    line: "--node-ip {{ ansible_default_ipv6.address }},{{ ansible_default_ipv4.address }}"
  notify: Restart Microk8s

- name: Post config handler flush
  meta: flush_handlers
