---
- name: Install Microk8s
  community.general.snap:
    channel: 1.22/stable
    classic: true
    state: present
    name: microk8s
  notify: Wait for Microk8s to start
  tags: microk8s
  become: yes
  register: installation

- name: Set new_cluster variable
  ansible.builtin.set_fact:
    new_cluster: "{{ installation.changed }}"

- name: Add ubuntu to microk8s group
  ansible.builtin.user:
    name: ubuntu
    groups: microk8s
    append: yes
  become: yes

- name: Add DNS names
  ansible.builtin.blockinfile:
    path: /var/snap/microk8s/current/certs/csr.conf.template
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    insertafter: "^DNS.*$"
    block: |
      DNS.6 = k8s.pohina.io
  notify: Wait 10s
  become: yes

- name: Add monitoring parameters to kube-proxy
  ansible.builtin.blockinfile:
    path: /var/snap/microk8s/current/args/kube-proxy
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      --metrics-bind-address={{ ansible_default_ipv4.address }}:10249
  become: yes

- name: Add monitoring parameters to kube-scheduler
  ansible.builtin.blockinfile:
    path: /var/snap/microk8s/current/args/kube-scheduler
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      --bind-address={{ ansible_default_ipv4.address }}
  become: yes

- name: Add monitoring parameters to kube-controller-manager
  ansible.builtin.blockinfile:
    path: /var/snap/microk8s/current/args/kube-controller-manager
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      --authorization-always-allow-paths="/healthz,/readyz,/livez,/metrics"
  become: yes

- name: Post install handler flush
  meta: flush_handlers
