---
- name: Install Microk8s
  community.general.snap:
    channel: 1.20/stable
    classic: true
    state: present
    name: microk8s
  notify: Wait for Microk8s to start
  tags: microk8s
  become: yes

- name: Add ubuntu to microk8s group
  ansible.builtin.user:
    name: ubuntu
    groups: microk8s
    append: yes
  become: yes

- name: Add DNS names
  ansible.builtin.blockinfile:
    path: /var/snap/microk8s/current/certs/csr.conf.template
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    insertafter: "^DNS.*$"
    block: |
      DNS.6 = k8s.atk.works
  notify: Wait 30s

- name: Flush handlers
  meta: flush_handlers
