---
- name: Include install steps
  ansible.builtin.import_tasks: install.yml

- name: Include dualstack configuration
  ansible.builtin.import_tasks: configure_dualstack.yml

- name: Include clustering setup
  ansible.builtin.import_tasks: form_cluster.yml

- name: chown ~/.kube
  ansible.builtin.file:
    path: /home/ubuntu/.kube
    state: directory
    owner: ubuntu
    recurse: true
  become: yes

- name: Create kubectl alias
  ansible.builtin.lineinfile:
    path: /home/ubuntu/.bash_aliases
    line: alias kubectl="microk8s.kubectl"
