---
- name: Include install steps
  import_tasks: install.yml

- name: Include clustering steps
  import_tasks: form_cluster.yml
  run_once: yes
  when: new_cluster

- name: chown ~/.kube
  ansible.builtin.file:
    path: /home/ubuntu/.kube
    state: directory
    owner: ubuntu
    recurse: true
  become: yes

- name: Create kubectl alias
  ansible.builtin.lineinfile:
    path: /home/ubuntu/.bash_aliases
    line: alias kubectl="microk8s.kubectl"

- name: Enable basic plugins
  command: "microk8s.enable {{ item }}"
  environment:
    LC_ALL: C.UTF-8
    LANG: C.UTF-8
  register: output
  changed_when: "'is already enabled' not in output.stdout_lines|list|first"
  loop:
    - "rbac"
    - "dns:172.23.100.1"
    - helm3
  loop_control:
    label: "{{ item }}"
  run_once: yes
  become: yes
