---
- name: Install utilities
  ansible.builtin.apt:
    name:
      - vim
      - htop
    state: present
  become: yes

- name: Create .bash_aliases
  ansible.builtin.file:
    path: /home/ubuntu/.bash_aliases
    owner: ubuntu
    group: ubuntu
    mode: u=rw,g=rw,o=r
