- name: Create /tmp/calico
  ansible.builtin.file:
    path: /tmp/calico
    state: directory
    owner: ubuntu
    group: microk8s
    mode: "0755"
  become: yes

- name: Copy files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/tmp/calico/{{ item }}"
    mode: "0775"
  loop:
    - calicoctl.yaml
    - config.patch
    - node.patch
  loop_control:
    label: "{{ item }}"

- name: Apply config.patch
  command: microk8s.kubectl patch -n kube-system configmaps/calico-config --patch-file=/tmp/calico/config.patch
  register: output
  changed_when: "'(no change)' not in output.stdout_lines|list|first"

- name: Apply node.patch
  command: microk8s.kubectl patch -n kube-system daemonset/calico-node  --patch-file=/tmp/calico/node.patch
  register: output
  changed_when: "'(no change)' not in output.stdout_lines|list|first"

- name: Deploy calicoctl
  command: microk8s.kubectl apply -f /tmp/calico/calicoctl.yaml

- name: Wait for calicoctl to be ready
  command: microk8s.kubectl wait --for=condition=ready pod -l app=calicoctl -n kube-system

- name: Add natOutgoing to ipv6-pool
  shell: |
    microk8s.kubectl exec -i -n kube-system calicoctl -- /calicoctl replace -f - << EOF
    apiVersion: projectcalico.org/v3
    kind: IPPool
    metadata:
      name: default-ipv6-ippool
    spec:
      blockSize: 122
      cidr: fd01::/64
      ipipMode: Never
      nodeSelector: all()
      vxlanMode: Never
      natOutgoing: true
    EOF
